name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run check-types
      - name: Run tests
        run: npm test
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run tests on Node.js 14
        run: npm test
